workflows:
  ios-ipa:
    name: iOS IPA Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build iOS IPA (Unsigned)
        script: flutter build ios --release --no-codesign
      - name: Create IPA
        script: |
          xcode-project use-latest
          xcode-project build-ipa --workspace="ios/Runner.xcworkspace" --scheme="Runner"
    artifacts:
      - build/ios/ipa/**/*.ipa